// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ezxrjflznhydrmmblxni.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV6eHJqZmx6bmh5ZHJtbWJseG5pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk1OTc4MjcsImV4cCI6MjA3NTE3MzgyN30.Ks6S9wl9tvG-A5gx1rCnYiV4XTiuk7YYwHLLwaFuw-g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
